export const data = {
    "Rekayasa Perangkat Lunak (RPL)": {
        "Algorithm": "A step-by-step procedure for solving a problem (Langkah demi langkah untuk menyelesaikan masalah).",
        "API": "Application Programming Interface, a set of rules for building software (Antarmuka Pemrograman Aplikasi, seperangkat aturan untuk membangun perangkat lunak).",
        "Bug": "An error in the software that causes it to malfunction (Kesalahan dalam perangkat lunak yang menyebabkan malfungsi).",
        "Code": "Instructions written in a programming language (Instruksi yang ditulis dalam bahasa pemrograman).",
        "Debugging": "The process of finding and fixing errors in code (Proses menemukan dan memperbaiki kesalahan dalam kode).",
        "Framework": "A structured platform for developing software (Platform terstruktur untuk mengembangkan perangkat lunak).",
        "Function": "A block of code designed to perform a specific task (Sekumpulan kode yang dirancang untuk melakukan tugas tertentu).",
        "Library": "A collection of pre-written code used to perform common tasks (Kumpulan kode yang telah ditulis sebelumnya digunakan untuk melakukan tugas umum).",
        "Object-Oriented Programming": "A programming paradigm based on objects and classes (Paradigma pemrograman yang berbasis pada objek dan kelas).",
        "Parameter": "A variable used in a function to receive input (Variabel yang digunakan dalam fungsi untuk menerima input).",
        "Refactoring": "The process of restructuring existing code without changing its behavior (Proses merestrukturisasi kode yang ada tanpa mengubah perilakunya).",
        "Repository": "A storage location for code and related files (Tempat penyimpanan untuk kode dan file terkait).",
        "Scalability": "The capability of a system to handle increased load (Kemampuan sistem untuk menangani beban yang meningkat).",
        "Syntax": "The set of rules that defines the structure of code (Sekumpulan aturan yang mendefinisikan struktur kode).",
        "Variable": "A storage location identified by a name that holds a value (Tempat penyimpanan yang diidentifikasi dengan nama yang menyimpan nilai).",
        "Version Control": "A system that tracks changes to files and allows for reverting to previous versions (Sistem yang melacak perubahan pada file dan memungkinkan untuk kembali ke versi sebelumnya).",
        "Loop": "A control structure that repeats a block of code (Struktur kontrol yang mengulangi sekumpulan kode).",
        "Conditional Statement": "A statement that executes code based on whether a condition is true or false (Pernyataan yang menjalankan kode berdasarkan apakah kondisi benar atau salah).",
        "Class": "A blueprint for creating objects, defining their properties and behaviors (Cetak biru untuk membuat objek, mendefinisikan properti dan perilaku mereka).",
        "Object": "An instance of a class that encapsulates data and methods (Instansi dari kelas yang mengenkapsulasi data dan metode).",
        "Inheritance": "A mechanism where a new class derives properties and behaviors from an existing class (Mekanisme di mana kelas baru mewarisi properti dan perilaku dari kelas yang ada).",
        "Polymorphism": "The ability of different classes to be treated as instances of the same class through a common interface (Kemampuan kelas yang berbeda untuk diperlakukan sebagai instansi dari kelas yang sama melalui antarmuka umum).",
        "Encapsulation": "The concept of bundling data and methods that operate on the data within one unit (Konsep menggabungkan data dan metode yang beroperasi pada data dalam satu unit).",
        "Abstraction": "The concept of hiding complex implementation details and showing only the necessary features (Konsep menyembunyikan detail implementasi yang kompleks dan hanya menampilkan fitur yang diperlukan).",
        "Instance": "A concrete occurrence of any object created based on a class (Kejadian konkrit dari objek yang dibuat berdasarkan kelas).",
        "Constructor": "A special function used to initialize objects (Fungsi khusus yang digunakan untuk menginisialisasi objek).",
        "Destructor": "A special function used to clean up an object before it is destroyed (Fungsi khusus yang digunakan untuk membersihkan objek sebelum dihancurkan).",
        "Overloading": "A feature that allows multiple methods with the same name but different parameters (Fitur yang memungkinkan beberapa metode dengan nama yang sama tetapi parameter yang berbeda).",
        "Overriding": "A feature that allows a subclass to provide a specific implementation of a method already defined in its superclass (Fitur yang memungkinkan subclass untuk menyediakan implementasi khusus dari metode yang sudah didefinisikan di superclass-nya).",
        "Exception Handling": "A mechanism to handle runtime errors and exceptions in a controlled manner (Mekanisme untuk menangani kesalahan dan pengecualian runtime dengan cara yang terkontrol).",
        "Testing": "The process of verifying that software functions correctly and meets requirements (Proses memverifikasi bahwa perangkat lunak berfungsi dengan benar dan memenuhi persyaratan).",
        "Unit Test": "A test that checks the functionality of a specific part of the code (Tes yang memeriksa fungsionalitas bagian tertentu dari kode).",
        "Integration Test": "A test that ensures different parts of a system work together (Tes yang memastikan berbagai bagian sistem bekerja bersama).",
        "System Test": "A test that evaluates the complete and integrated software system (Tes yang mengevaluasi sistem perangkat lunak yang lengkap dan terintegrasi).",
        "User Acceptance Test": "A test conducted by end-users to ensure the system meets their needs (Tes yang dilakukan oleh pengguna akhir untuk memastikan sistem memenuhi kebutuhan mereka).",
        "Deployment": "The process of delivering and installing software on a target environment (Proses pengiriman dan pemasangan perangkat lunak di lingkungan target).",
        "Maintenance": "The process of fixing issues and updating software after it has been deployed (Proses memperbaiki masalah dan memperbarui perangkat lunak setelah diterapkan).",
        "Documentation": "Written information that describes how software works and how to use it (Informasi tertulis yang menjelaskan cara kerja perangkat lunak dan cara menggunakannya).",
        "Architecture": "The high-level design of a software system, defining its structure and components (Desain tingkat tinggi dari sistem perangkat lunak, mendefinisikan struktur dan komponennya).",
        "Design Pattern": "A reusable solution to a common problem in software design (Solusi yang dapat digunakan kembali untuk masalah umum dalam desain perangkat lunak).",
        "Agile": "A methodology that emphasizes iterative development and collaboration (Metodologi yang menekankan pengembangan iteratif dan kolaborasi).",
        "Scrum": "An Agile framework for managing and completing complex projects (Kerangka kerja Agile untuk mengelola dan menyelesaikan proyek yang kompleks).",
        "Kanban": "A visual method for managing work in progress (Metode visual untuk mengelola pekerjaan yang sedang berjalan).",
        "Continuous Integration": "The practice of frequently integrating code changes into a shared repository (Praktik sering mengintegrasikan perubahan kode ke dalam repositori bersama).",
        "Continuous Deployment": "The practice of automatically deploying code changes to production (Praktik secara otomatis menerapkan perubahan kode ke produksi).",
        "Microservices": "An architectural style that structures an application as a collection of small, loosely coupled services (Gaya arsitektur yang menyusun aplikasi sebagai kumpulan layanan kecil yang terpisah).",
        "Containerization": "The process of packaging software to run consistently across different environments (Proses mengemas perangkat lunak agar dapat berjalan secara konsisten di berbagai lingkungan).",
        "DevOps": "A set of practices that combine software development and IT operations (Sekumpulan praktik yang menggabungkan pengembangan perangkat lunak dan operasi TI).",
        "Cloud Computing": "The delivery of computing services over the internet (Penyampaian layanan komputasi melalui internet).",
        "Database": "A structured collection of data stored and accessed electronically (Kumpulan data terstruktur yang disimpan dan diakses secara elektronik).",
        "SQL": "Structured Query Language, used for managing and manipulating relational databases (Bahasa Kueri Terstruktur, digunakan untuk mengelola dan memanipulasi basis data relasional).",
        "NoSQL": "A category of databases that do not use SQL for querying (Kategori basis data yang tidak menggunakan SQL untuk kueri).",
        "Normalization": "The process of organizing data to minimize redundancy (Proses mengorganisir data untuk meminimalkan redundansi).",
        "Denormalization": "The process of merging data to improve read performance (Proses menggabungkan data untuk meningkatkan kinerja baca).",
        "Indexing": "A technique to improve database query performance (Teknik untuk meningkatkan kinerja kueri basis data).",
        "Backup": "A copy of data stored to prevent loss in case of failure (Salinan data yang disimpan untuk mencegah kehilangan jika terjadi kegagalan).",
        "Encryption": "The process of converting data into a secure format to prevent unauthorized access (Proses mengubah data menjadi format yang aman untuk mencegah akses tidak sah).",
        "Authentication": "The process of verifying the identity of a user or system (Proses memverifikasi identitas pengguna atau sistem).",
        "Authorization": "The process of granting or denying access to resources based on permissions (Proses memberikan atau menolak akses ke sumber daya berdasarkan izin)."
    },
    "Teknik Komputer dan Jaringan (RPL)": {
        "Network": "A collection of interconnected devices that communicate with each other (Kumpulan perangkat yang saling terhubung dan berkomunikasi satu sama lain).",
        "Router": "A device that forwards data packets between computer networks (Perangkat yang meneruskan paket data antara jaringan komputer).",
        "Switch": "A device that connects multiple devices on a network and uses MAC addresses to forward data (Perangkat yang menghubungkan beberapa perangkat dalam jaringan dan menggunakan alamat MAC untuk meneruskan data).",
        "IP Address": "A unique address assigned to each device on a network for identification (Alamat unik yang diberikan kepada setiap perangkat di jaringan untuk identifikasi).",
        "Subnet": "A segment of a larger network, divided to improve performance and security (Segmen dari jaringan yang lebih besar, dibagi untuk meningkatkan kinerja dan keamanan).",
        "Gateway": "A network node that serves as an access point to another network (Node jaringan yang berfungsi sebagai titik akses ke jaringan lain).",
        "Firewall": "A security system that monitors and controls incoming and outgoing network traffic (Sistem keamanan yang memantau dan mengontrol lalu lintas jaringan yang masuk dan keluar).",
        "Bandwidth": "The maximum rate at which data can be transferred over a network (Kecepatan maksimum di mana data dapat ditransfer melalui jaringan).",
        "Latency": "The delay between sending and receiving data over a network (Keterlambatan antara pengiriman dan penerimaan data melalui jaringan).",
        "Protocol": "A set of rules that define how data is transmitted and received over a network (Sekumpulan aturan yang mendefinisikan cara data ditransmisikan dan diterima melalui jaringan).",
        "TCP/IP": "Transmission Control Protocol/Internet Protocol, a suite of protocols used for communication over the internet (Protokol Kontrol Transmisi/Protokol Internet, seperangkat protokol yang digunakan untuk komunikasi melalui internet).",
        "DNS": "Domain Name System, a system that translates domain names into IP addresses (Sistem Nama Domain, sistem yang menerjemahkan nama domain menjadi alamat IP).",
        "VPN": "Virtual Private Network, a technology that creates a secure network connection over a public network (Jaringan Pribadi Virtual, teknologi yang membuat koneksi jaringan aman melalui jaringan publik).",
        "Wi-Fi": "A wireless technology that allows devices to connect to a network using radio waves (Teknologi nirkabel yang memungkinkan perangkat terhubung ke jaringan menggunakan gelombang radio).",
        "Ethernet": "A wired networking technology used for local area networks (Teknologi jaringan kabel yang digunakan untuk jaringan area lokal).",
        "LAN": "Local Area Network, a network that connects devices within a limited area such as a building (Jaringan Area Lokal, jaringan yang menghubungkan perangkat dalam area terbatas seperti gedung).",
        "WAN": "Wide Area Network, a network that covers a large geographic area (Jaringan Area Luas, jaringan yang mencakup area geografis yang luas).",
        "Access Point": "A device that allows wireless devices to connect to a wired network using Wi-Fi (Perangkat yang memungkinkan perangkat nirkabel terhubung ke jaringan kabel menggunakan Wi-Fi).",
        "NAT": "Network Address Translation, a method of remapping one IP address space into another (Translasi Alamat Jaringan, metode pemetaan satu ruang alamat IP ke ruang lainnya).",
        "OSI Model": "Open Systems Interconnection Model, a conceptual framework for understanding network interactions (Model Interkoneksi Sistem Terbuka, kerangka konseptual untuk memahami interaksi jaringan).",
        "MAC Address": "Media Access Control Address, a unique identifier assigned to network interfaces (Alamat Kontrol Akses Media, pengidentifikasi unik yang diberikan ke antarmuka jaringan).",
        "Throughput": "The rate at which data is successfully transmitted over a network (Kecepatan di mana data berhasil ditransmisikan melalui jaringan).",
        "Proxy Server": "A server that acts as an intermediary between a client and a destination server (Server yang bertindak sebagai perantara antara klien dan server tujuan).",
        "Load Balancer": "A device that distributes network or application traffic across multiple servers (Perangkat yang mendistribusikan lalu lintas jaringan atau aplikasi ke beberapa server).",
        "Topology": "The arrangement of different elements (links, nodes, etc.) in a network (Pengaturan elemen yang berbeda (tautan, node, dll.) dalam jaringan).",
        "Fiber Optic": "A technology that uses light to transmit data over long distances (Teknologi yang menggunakan cahaya untuk mentransmisikan data jarak jauh).",
        "Modem": "A device that modulates and demodulates signals for data transmission over telephone lines (Perangkat yang memodulasi dan demodulasi sinyal untuk transmisi data melalui saluran telepon).",
        "Bandwidth Management": "The practice of optimizing and allocating bandwidth to prevent congestion (Praktik mengoptimalkan dan mengalokasikan bandwidth untuk mencegah kemacetan).",
        "Network Security": "Measures taken to protect a network from unauthorized access and attacks (Langkah-langkah yang diambil untuk melindungi jaringan dari akses tidak sah dan serangan).",
        "Packet": "A unit of data transmitted over a network (Unit data yang ditransmisikan melalui jaringan).",
        "Tunneling": "A method of sending data securely across a network by encapsulating it in another protocol (Metode mengirim data secara aman melalui jaringan dengan mengenkapsulasinya dalam protokol lain).",
        "Port": "A logical connection point used by network protocols to communicate (Titik koneksi logis yang digunakan oleh protokol jaringan untuk berkomunikasi).",
        "Jitter": "The variation in packet arrival times, which can affect network performance (Variasi dalam waktu kedatangan paket, yang dapat mempengaruhi kinerja jaringan).",
        "QoS": "Quality of Service, a measure of the performance of a network (Kualitas Layanan, ukuran kinerja jaringan).",
        "Data Encryption": "The process of converting data into a secure format to prevent unauthorized access (Proses mengubah data menjadi format aman untuk mencegah akses tidak sah).",
        "Virtualization": "The creation of virtual versions of physical devices or resources (Pembuatan versi virtual dari perangkat atau sumber daya fisik).",
        "Server": "A computer or system that provides resources, data, or services to other computers over a network (Komputer atau sistem yang menyediakan sumber daya, data, atau layanan kepada komputer lain melalui jaringan).",
        "Client": "A device or application that requests resources or services from a server (Perangkat atau aplikasi yang meminta sumber daya atau layanan dari server).",
        "Data Center": "A facility used to house computer systems and associated components (Fasilitas yang digunakan untuk menampung sistem komputer dan komponen terkait).",
    },
    "Teknik Las (TL)": {
        "Welding": "A process of joining materials, usually metals, by causing coalescence (Proses menyatukan bahan, biasanya logam, dengan menyebabkan koalesensi).",
        "Arc Welding": "A type of welding that uses an electric arc to melt and join metals (Jenis pengelasan yang menggunakan busur listrik untuk melelehkan dan menyatukan logam).",
        "MIG Welding": "Metal Inert Gas welding, a type of arc welding using a continuous wire feed (Pengelasan Gas Inert Logam, jenis pengelasan busur menggunakan umpan kawat kontinu).",
        "TIG Welding": "Tungsten Inert Gas welding, a type of arc welding with a tungsten electrode and an inert gas shield (Pengelasan Gas Inert Tungsten, jenis pengelasan busur dengan elektroda tungsten dan pelindung gas inert).",
        "Stick Welding": "Shielded Metal Arc Welding, a process using a consumable electrode coated with flux (Pengelasan Busur Logam Terlindung, proses menggunakan elektroda yang dapat dimakan yang dilapisi dengan fluks).",
        "Flux": "A chemical agent used to prevent oxidation and improve the quality of the weld (Agen kimia yang digunakan untuk mencegah oksidasi dan meningkatkan kualitas pengelasan).",
        "Electrode": "A conductor used to make contact with the welding arc and supply the filler material (Konduktor yang digunakan untuk membuat kontak dengan busur pengelasan dan memasok material pengisi).",
        "Filler Material": "Material added during welding to fill gaps and strengthen the joint (Material yang ditambahkan selama pengelasan untuk mengisi celah dan memperkuat sambungan).",
        "Weld Bead": "The layer of molten material deposited during the welding process (Lapisan material cair yang ditempatkan selama proses pengelasan).",
        "Heat Affected Zone": "The area of the base metal that has been altered by the welding process (Area logam dasar yang telah diubah oleh proses pengelasan).",
        "Weld Joint": "The location where two pieces of metal are joined together (Tempat di mana dua potong logam disatukan).",
        "Torch": "A tool used to direct the welding arc and control the heat (Alat yang digunakan untuk mengarahkan busur pengelasan dan mengontrol panas).",
        "Safety Gear": "Protective equipment worn to prevent injury during welding (Perlengkapan pelindung yang dikenakan untuk mencegah cedera selama pengelasan).",
        "Shielding Gas": "A gas used to protect the weld area from contamination and oxidation (Gas yang digunakan untuk melindungi area pengelasan dari kontaminasi dan oksidasi).",
        "Welding Position": "The orientation of the workpieces during the welding process (Orientasi benda kerja selama proses pengelasan).",
        "Weld Penetration": "The depth to which the weld metal has fused into the base material (Kedalaman di mana logam pengelasan telah menyatu dengan material dasar).",
        "Weld Size": "The dimensions of the weld bead, including its width and height (Dimensi dari bead pengelasan, termasuk lebar dan tingginya).",
        "Preheat": "The process of heating the base metal before welding to prevent thermal shock (Proses memanaskan logam dasar sebelum pengelasan untuk mencegah kejutan termal).",
        "Post-Weld Heat Treatment": "A heat treatment applied after welding to relieve stresses and improve mechanical properties (Perlakuan panas yang diterapkan setelah pengelasan untuk mengurangi tegangan dan meningkatkan sifat mekanis).",
        "Welding Procedure": "A set of instructions outlining the steps and parameters for performing a specific weld (Sekumpulan instruksi yang menjelaskan langkah-langkah dan parameter untuk melakukan pengelasan tertentu).",
        "Welding Rod": "A rod of filler material used in some welding processes (Batang material pengisi yang digunakan dalam beberapa proses pengelasan).",
        "Welding Machine": "The equipment used to generate the electric arc and control the welding process (Peralatan yang digunakan untuk menghasilkan busur listrik dan mengontrol proses pengelasan).",
        "Welding Defects": "Imperfections in the weld such as cracks, porosity, or incomplete fusion (Ketidaksempurnaan dalam pengelasan seperti retakan, porositas, atau penggabungan yang tidak lengkap).",
        "Weld Inspection": "The process of examining the weld to ensure it meets the required standards (Proses memeriksa pengelasan untuk memastikan memenuhi standar yang diperlukan).",
        "Welding Symbol": "A standardized symbol used on drawings to indicate welding requirements (Simbol standar yang digunakan pada gambar untuk menunjukkan persyaratan pengelasan).",
        "Tensile Strength": "The maximum amount of tensile stress a material can withstand before failing (Jumlah maksimum tegangan tarik yang dapat ditahan material sebelum gagal).",
        "Ductility": "The ability of a material to deform under tensile stress without breaking (Kemampuan material untuk mengalami deformasi di bawah tegangan tarik tanpa patah).",
        "Impact Test": "A test to determine a material's ability to withstand impact forces (Tes untuk menentukan kemampuan material dalam menahan gaya benturan).",
        "Welding Consumables": "Materials such as electrodes and filler rods used during the welding process (Material seperti elektroda dan batang pengisi yang digunakan selama proses pengelasan).",
        "Welding Safety": "Practices and precautions taken to prevent accidents and injuries during welding (Praktik dan langkah-langkah pencegahan yang diambil untuk mencegah kecelakaan dan cedera selama pengelasan).",
        "Arc Length": "The distance between the welding electrode and the workpiece (Jarak antara elektroda pengelasan dan benda kerja).",
        "Weld Pool": "The molten metal created during the welding process (Logam cair yang dibuat selama proses pengelasan).",
        "Gas Flow Rate": "The rate at which shielding gas is delivered to the weld area (Kecepatan di mana gas pelindung disalurkan ke area pengelasan).",
        "Weld Groove": "A preparation made in the base metal to improve weld penetration (Persiapan yang dibuat pada logam dasar untuk meningkatkan penetrasi pengelasan).",
        "Welding Positioner": "A device used to hold and manipulate the workpiece during welding (Perangkat yang digunakan untuk menahan dan memanipulasi benda kerja selama pengelasan).",
        "Welding Technique": "The method and approach used to perform a weld effectively (Metode dan pendekatan yang digunakan untuk melakukan pengelasan secara efektif).",
        "Joint Design": "The configuration of the metal parts to be welded together (Konfigurasi bagian logam yang akan dilas bersama).",
        "Weld Contour": "The shape and finish of the weld bead (Bentuk dan hasil akhir bead pengelasan).",
        "Backstep Welding": "A technique where welding starts from the end of the joint and works backward (Teknik di mana pengelasan dimulai dari akhir sambungan dan bekerja mundur).",
        "Weaving": "A technique where the welding torch is moved side to side to improve bead formation (Teknik di mana obor pengelasan digerakkan ke kiri dan ke kanan untuk meningkatkan pembentukan bead)."
    },
    "Desain Pemodelan dan Informasi Bangunan (DPIB)": {
        "Building Information Modeling (BIM)": "A digital representation of the physical and functional characteristics of a building (Representasi digital dari karakteristik fisik dan fungsional sebuah bangunan).",
        "3D Modeling": "The process of creating a three-dimensional representation of a physical object (Proses membuat representasi tiga dimensi dari objek fisik).",
        "Parametric Design": "A design methodology where parameters define the relationships between different components (Metodologi desain di mana parameter mendefinisikan hubungan antara komponen yang berbeda).",
        "Architectural Visualization": "The creation of visual representations of architectural designs (Pembuatan representasi visual dari desain arsitektur).",
        "Drafting": "The process of creating detailed drawings of buildings and structures (Proses membuat gambar rinci dari bangunan dan struktur).",
        "Construction Documentation": "Detailed drawings and specifications used during the construction phase (Gambar rinci dan spesifikasi yang digunakan selama fase konstruksi).",
        "Site Analysis": "The process of evaluating a site for its suitability for construction (Proses mengevaluasi lokasi untuk kecocokannya untuk konstruksi).",
        "Structural Analysis": "The assessment of a building's structural integrity and stability (Penilaian integritas dan stabilitas struktural bangunan).",
        "Energy Modeling": "The simulation of a building's energy use to improve efficiency (Simulasi penggunaan energi sebuah bangunan untuk meningkatkan efisiensi).",
        "Material Specification": "The detailed description of materials to be used in construction (Deskripsi rinci tentang material yang akan digunakan dalam konstruksi).",
        "Building Codes": "Regulations and standards governing the construction and design of buildings (Regulasi dan standar yang mengatur konstruksi dan desain bangunan).",
        "Lifecycle Management": "Managing the entire lifecycle of a building from design to demolition (Mengelola seluruh siklus hidup bangunan dari desain hingga pembongkaran).",
        "Collaborative Design": "A design approach where multiple stakeholders work together to develop solutions (Pendekatan desain di mana berbagai pemangku kepentingan bekerja sama untuk mengembangkan solusi).",
        "Construction Sequencing": "The planning and scheduling of construction activities to ensure efficient workflow (Perencanaan dan penjadwalan aktivitas konstruksi untuk memastikan alur kerja yang efisien).",
        "Building Envelope": "The physical barrier between the interior and exterior of a building (Penghalang fisik antara interior dan eksterior bangunan).",
        "Space Planning": "The process of organizing interior spaces to optimize functionality and efficiency (Proses mengatur ruang interior untuk mengoptimalkan fungsionalitas dan efisiensi).",
        "Quantity Takeoff": "The process of measuring and calculating the quantities of materials needed for construction (Proses mengukur dan menghitung jumlah material yang dibutuhkan untuk konstruksi).",
        "Design Intent": "The goals and objectives a designer aims to achieve with a project (Tujuan dan sasaran yang ingin dicapai desainer dengan proyek).",
        "Virtual Reality (VR)": "Technology that creates immersive digital environments for visualization and simulation (Teknologi yang menciptakan lingkungan digital imersif untuk visualisasi dan simulasi).",
        "Augmented Reality (AR)": "Technology that overlays digital information on the real world for enhanced visualization (Teknologi yang menambahkan informasi digital di atas dunia nyata untuk visualisasi yang ditingkatkan).",
        "Clash Detection": "The process of identifying conflicts between building systems or components in a model (Proses mengidentifikasi konflik antara sistem atau komponen bangunan dalam model).",
        "Integration": "Combining various design and construction disciplines into a unified model (Menggabungkan berbagai disiplin desain dan konstruksi ke dalam model yang terintegrasi).",
        "Simulation": "The use of models to predict the performance of building systems under various conditions (Penggunaan model untuk memprediksi kinerja sistem bangunan di bawah berbagai kondisi).",
        "Smart Building": "A building equipped with advanced systems and controls for improved efficiency and functionality (Bangunan yang dilengkapi dengan sistem dan kontrol canggih untuk efisiensi dan fungsionalitas yang lebih baik).",
        "Digital Twin": "A digital replica of a physical building used for monitoring and simulation (Replika digital dari bangunan fisik yang digunakan untuk pemantauan dan simulasi).",
        "Facilities Management": "The management of building operations and maintenance to ensure functionality and efficiency (Manajemen operasi dan pemeliharaan bangunan untuk memastikan fungsionalitas dan efisiensi).",
        "BIM Coordination": "The process of aligning and synchronizing multiple BIM models from different disciplines (Proses menyelaraskan dan menyinkronkan beberapa model BIM dari berbagai disiplin).",
        "Building Simulation": "The use of software to model and analyze the performance of a building (Penggunaan perangkat lunak untuk memodelkan dan menganalisis kinerja bangunan).",
        "Sustainability": "Design and construction practices aimed at minimizing environmental impact and maximizing resource efficiency (Praktik desain dan konstruksi yang bertujuan mengurangi dampak lingkungan dan memaksimalkan efisiensi sumber daya).",
        "Constructability": "The ease with which a building can be constructed according to the design and specifications (Kemudahan di mana sebuah bangunan dapat dibangun sesuai dengan desain dan spesifikasi).",
        "Building Lifecycle": "The phases of a building's existence from planning through demolition (Fase-fase keberadaan bangunan dari perencanaan hingga pembongkaran).",
        "Code Compliance": "Ensuring that a building meets all applicable codes and regulations (Memastikan bahwa bangunan memenuhi semua kode dan regulasi yang berlaku).",
        "Energy Efficiency": "The practice of using less energy to provide the same level of service (Praktik menggunakan lebih sedikit energi untuk memberikan tingkat layanan yang sama).",
        "Project Management": "The process of planning, organizing, and overseeing a construction project from start to finish (Proses perencanaan, pengorganisasian, dan pengawasan proyek konstruksi dari awal hingga akhir).",
        "Construction Cost Estimation": "The process of predicting the cost of a construction project based on various factors (Proses memperkirakan biaya proyek konstruksi berdasarkan berbagai faktor)."
    },
    "Geomatika": {
        "Geodesy": "The science of measuring and understanding the Earth's geometric shape, orientation, and gravity field (Ilmu tentang pengukuran dan pemahaman bentuk geometri Bumi, orientasi, dan medan gravitasi).",
        "Geographic Information System (GIS)": "A system designed to capture, store, analyze, and manage spatial and geographic data (Sistem yang dirancang untuk menangkap, menyimpan, menganalisis, dan mengelola data spasial dan geografis).",
        "Remote Sensing": "The acquisition of information about an object or phenomenon without making physical contact (Perolehan informasi tentang objek atau fenomena tanpa melakukan kontak fisik).",
        "Cartography": "The art and science of map-making, including the design and production of maps (Seni dan ilmu pembuatan peta, termasuk desain dan produksi peta).",
        "Coordinate System": "A system that uses numbers or coordinates to uniquely identify locations in space (Sistem yang menggunakan angka atau koordinat untuk mengidentifikasi lokasi secara unik dalam ruang).",
        "Latitude": "The geographic coordinate that specifies the north-south position of a point on the Earth's surface (Koordinat geografis yang menentukan posisi utara-selatan dari suatu titik di permukaan Bumi).",
        "Longitude": "The geographic coordinate that specifies the east-west position of a point on the Earth's surface (Koordinat geografis yang menentukan posisi timur-barat dari suatu titik di permukaan Bumi).",
        "Elevation": "The height of a point above a reference level, usually sea level (Ketinggian suatu titik di atas level referensi, biasanya permukaan laut).",
        "Geodetic Datum": "A reference system used to define the location of geographic features (Sistem referensi yang digunakan untuk mendefinisikan lokasi fitur geografis).",
        "Surveying": "The process of measuring and mapping the Earth's surface and its features (Proses mengukur dan memetakan permukaan Bumi dan fiturnya).",
        "Triangulation": "A method of determining the location of a point by measuring angles from known points (Metode menentukan lokasi titik dengan mengukur sudut dari titik-titik yang diketahui).",
        "LiDAR": "Light Detection and Ranging, a remote sensing method that uses laser pulses to measure distances to the Earth's surface (Metode penginderaan jauh yang menggunakan pulsa laser untuk mengukur jarak ke permukaan Bumi).",
        "GPS": "Global Positioning System, a satellite-based navigation system used for determining precise locations (Sistem Navigasi Global, sistem berbasis satelit yang digunakan untuk menentukan lokasi dengan tepat).",
        "Topography": "The arrangement of natural and artificial features on the Earth's surface (Pengaturan fitur alami dan buatan di permukaan Bumi).",
        "Geospatial Data": "Data related to geographic locations and features (Data yang terkait dengan lokasi dan fitur geografis).",
        "Orthophoto": "An aerial photograph that has been geometrically corrected to have a uniform scale (Foto udara yang telah dikoreksi secara geometris untuk memiliki skala seragam).",
        "Digital Elevation Model (DEM)": "A 3D representation of terrain surfaces created from terrain elevation data (Representasi 3D dari permukaan terrain yang dibuat dari data ketinggian terrain).",
        "Mapping Projection": "The method of representing the curved surface of the Earth on a flat map (Metode mewakili permukaan melengkung Bumi pada peta datar).",
        "Georeferencing": "The process of aligning spatial data to a known coordinate system (Proses menyelaraskan data spasial ke sistem koordinat yang diketahui).",
        "Spatial Analysis": "The examination of spatial relationships to understand patterns and processes (Pemeriksaan hubungan spasial untuk memahami pola dan proses).",
        "Photogrammetry": "The science of making measurements from photographs, especially for creating maps (Ilmu tentang membuat pengukuran dari foto, terutama untuk membuat peta).",
        "Geological Mapping": "The process of creating maps that show the distribution and structure of geological features (Proses membuat peta yang menunjukkan distribusi dan struktur fitur geologi).",
        "Map Scale": "The ratio of a distance on the map to the corresponding distance on the ground (Rasio jarak pada peta dengan jarak yang sesuai di lapangan).",
        "Spatial Data Infrastructure (SDI)": "A framework for managing and sharing spatial data among different organizations (Kerangka kerja untuk mengelola dan berbagi data spasial di antara berbagai organisasi).",
        "Geospatial Analysis": "The process of analyzing spatial data to solve problems and make decisions (Proses menganalisis data spasial untuk memecahkan masalah dan membuat keputusan).",
        "Geostatistics": "The branch of statistics focusing on spatial or spatiotemporal datasets (Cabang statistik yang fokus pada dataset spasial atau spatiotemporal).",
        "Spatial Resolution": "The level of detail in spatial data, determined by the size of the smallest unit of measurement (Tingkat detail dalam data spasial, ditentukan oleh ukuran unit pengukuran terkecil).",
        "Vector Data": "Data representation using points, lines, and polygons to represent spatial features (Representasi data menggunakan titik, garis, dan poligon untuk mewakili fitur spasial).",
        "Raster Data": "Data representation using a grid of cells or pixels, commonly used in remote sensing (Representasi data menggunakan grid sel atau piksel, umumnya digunakan dalam penginderaan jauh).",
        "Georeferenced Imagery": "Images that have been aligned to a coordinate system for spatial analysis (Gambar yang telah diselaraskan dengan sistem koordinat untuk analisis spasial).",
        "Boundary Mapping": "The process of defining and mapping the boundaries of geographic or political regions (Proses mendefinisikan dan memetakan batas-batas wilayah geografis atau politik).",
        "Land Use Planning": "The process of managing land resources for various purposes like agriculture, urban development, and conservation (Proses mengelola sumber daya lahan untuk berbagai tujuan seperti pertanian, pengembangan kota, dan konservasi).",
        "Geospatial Intelligence": "The collection and analysis of geographic data to support decision-making (Pengumpulan dan analisis data geografis untuk mendukung pengambilan keputusan).",
        "Spatial Data Collection": "The process of gathering geographic and spatial data through various methods (Proses mengumpulkan data geografis dan spasial melalui berbagai metode)."
    },
    "Teknik Instalasi Tenaga Listrik (TITL)": {
        "Electrical Wiring": "The process of installing electrical cables and connections in buildings (Proses pemasangan kabel dan sambungan listrik di bangunan).",
        "Circuit Breaker": "A device that automatically interrupts the electrical circuit to prevent overloads and short circuits (Perangkat yang secara otomatis memutuskan sirkuit listrik untuk mencegah kelebihan beban dan korsleting).",
        "Transformer": "A device used to change the voltage level in an electrical circuit (Perangkat yang digunakan untuk mengubah level tegangan dalam sirkuit listrik).",
        "Power Distribution": "The process of delivering electrical power from generation sources to end users (Proses pengiriman tenaga listrik dari sumber pembangkit ke pengguna akhir).",
        "Electrical Panel": "A box that houses circuit breakers or fuses to protect and control the electrical circuits (Kotak yang berisi pemutus sirkuit atau sekering untuk melindungi dan mengontrol sirkuit listrik).",
        "Grounding": "The process of creating a safe path for electrical current to flow into the earth (Proses menciptakan jalur aman bagi arus listrik untuk mengalir ke tanah).",
        "Voltage": "The electrical potential difference between two points in a circuit (Perbedaan potensi listrik antara dua titik dalam sirkuit).",
        "Current": "The flow of electric charge through a conductor (Aliran muatan listrik melalui konduktor).",
        "Resistance": "The opposition to the flow of electric current, measured in ohms (Penolakan terhadap aliran arus listrik, diukur dalam ohm).",
        "Insulation": "Material used to prevent the loss of electrical energy and protect against electrical shock (Material yang digunakan untuk mencegah kehilangan energi listrik dan melindungi dari kejutan listrik).",
        "Conduit": "A protective tube through which electrical cables are run (Tabung pelindung tempat kabel listrik diletakkan).",
        "Circuit": "A complete path through which electricity flows (Jalur lengkap tempat listrik mengalir).",
        "Switch": "A device used to open or close an electrical circuit (Perangkat yang digunakan untuk membuka atau menutup sirkuit listrik).",
        "Socket": "A receptacle that allows electrical devices to be connected to the power supply (Tempat yang memungkinkan perangkat listrik terhubung ke pasokan listrik).",
        "Fuse": "A safety device that melts and breaks the circuit when excessive current flows through it (Perangkat pengaman yang mencair dan memutuskan sirkuit saat arus berlebih mengalir melaluinya).",
        "Load": "The amount of electrical power consumed by devices or appliances (Jumlah daya listrik yang dikonsumsi oleh perangkat atau peralatan).",
        "Power Factor": "The ratio of real power to apparent power in an electrical system (Rasio daya nyata terhadap daya semu dalam sistem listrik).",
        "Ampere": "A unit of electrical current (Satuan arus listrik).",
        "Watt": "A unit of electrical power, equivalent to one joule per second (Satuan daya listrik, setara dengan satu joule per detik).",
        "Hertz": "The unit of frequency, representing the number of cycles per second (Satuan frekuensi, mewakili jumlah siklus per detik).",
        "Electrical Load Calculation": "The process of determining the total power requirements for a building or system (Proses menentukan kebutuhan daya total untuk bangunan atau sistem).",
        "Short Circuit": "An unintended connection between two points in a circuit that causes excessive current flow (Koneksi yang tidak diinginkan antara dua titik dalam sirkuit yang menyebabkan aliran arus berlebih).",
        "Overload": "A condition where the electrical demand exceeds the capacity of the circuit (Kondisi di mana permintaan listrik melebihi kapasitas sirkuit).",
        "Electrical Safety": "Practices and precautions taken to prevent electrical hazards and accidents (Praktik dan langkah-langkah pencegahan yang diambil untuk mencegah bahaya dan kecelakaan listrik).",
        "Voltage Drop": "The reduction in voltage in an electrical circuit due to resistance (Pengurangan tegangan dalam sirkuit listrik karena resistansi).",
        "Electrical Code": "A set of standards and regulations governing electrical installations (Sekumpulan standar dan regulasi yang mengatur instalasi listrik).",
        "Transformer Rating": "The specification indicating the maximum power or voltage a transformer can handle (Spesifikasi yang menunjukkan daya maksimum atau tegangan yang dapat ditangani oleh transformer).",
        "Cable Tray": "A support system for managing and routing electrical cables (Sistem dukungan untuk mengelola dan merutekan kabel listrik).",
        "Lighting Design": "The process of planning and designing the illumination of a space (Proses perencanaan dan desain pencahayaan suatu ruangan).",
        "Earthing": "The process of connecting the non-current carrying parts of electrical equipment to the ground (Proses menghubungkan bagian peralatan listrik yang tidak membawa arus ke tanah).",
        "Electric Meter": "A device that measures the amount of electrical energy consumed (Perangkat yang mengukur jumlah energi listrik yang dikonsumsi).",
        "Surge Protection": "Devices and techniques used to protect electrical systems from voltage spikes (Perangkat dan teknik yang digunakan untuk melindungi sistem listrik dari lonjakan tegangan).",
        "Electrical Circuit Design": "The process of planning and creating electrical circuits to meet specific requirements (Proses merencanakan dan membuat sirkuit listrik untuk memenuhi persyaratan tertentu).",
        "Panelboard": "An assembly of circuit breakers or fuses that distributes electrical power to various circuits (Rangkaian pemutus sirkuit atau sekering yang mendistribusikan daya listrik ke berbagai sirkuit)."
    },
    "Teknik Audio Video (TAV)": {
        "Audio Mixing": "The process of combining multiple audio tracks into a single audio output (Proses menggabungkan beberapa trek audio menjadi satu output audio).",
        "Video Editing": "The process of cutting, arranging, and modifying video footage to create a final product (Proses memotong, menyusun, dan memodifikasi rekaman video untuk membuat produk akhir).",
        "Sound Engineering": "The application of audio technology and techniques to record, mix, and produce sound (Penerapan teknologi dan teknik audio untuk merekam, mencampur, dan memproduksi suara).",
        "Broadcasting": "The distribution of audio and video content to a wide audience via radio, television, or internet (Distribusi konten audio dan video ke audiens yang luas melalui radio, televisi, atau internet).",
        "Video Projection": "The process of displaying video content onto a surface using a projector (Proses menampilkan konten video ke permukaan menggunakan proyektor).",
        "Microphone": "A device used to capture and convert sound waves into an electrical signal (Perangkat yang digunakan untuk menangkap dan mengubah gelombang suara menjadi sinyal listrik).",
        "Audio Interface": "A device that connects audio equipment to a computer for recording and playback (Perangkat yang menghubungkan peralatan audio ke komputer untuk perekaman dan pemutaran).",
        "Mixing Console": "A device used to control and adjust audio signals from various sources (Perangkat yang digunakan untuk mengontrol dan menyesuaikan sinyal audio dari berbagai sumber).",
        "Video Camera": "A device used to capture moving images and record video footage (Perangkat yang digunakan untuk menangkap gambar bergerak dan merekam rekaman video).",
        "Signal Processing": "The manipulation of audio or video signals to enhance or modify their characteristics (Manipulasi sinyal audio atau video untuk meningkatkan atau memodifikasi karakteristiknya).",
        "Lighting Design": "The process of planning and arranging lighting to achieve desired visual effects (Proses perencanaan dan pengaturan pencahayaan untuk mencapai efek visual yang diinginkan).",
        "Audio Compression": "The process of reducing the size of an audio file while maintaining quality (Proses mengurangi ukuran file audio sambil mempertahankan kualitas).",
        "Video Encoding": "The process of converting video files into a specific format for storage or transmission (Proses mengonversi file video ke format tertentu untuk penyimpanan atau transmisi).",
        "Soundproofing": "The process of reducing or eliminating sound transmission between spaces (Proses mengurangi atau menghilangkan transmisi suara antara ruang).",
        "Editing Software": "Programs used to cut, arrange, and enhance audio and video content (Program yang digunakan untuk memotong, menyusun, dan meningkatkan konten audio dan video).",
        "Broadcast Audio": "Audio content transmitted to an audience via radio or television (Konten audio yang ditransmisikan kepada audiens melalui radio atau televisi).",
        "HD Video": "High Definition video with enhanced resolution and clarity (Video Definisi Tinggi dengan resolusi dan kejernihan yang ditingkatkan).",
        "Live Sound": "Audio engineering and management for live events and performances (Rekayasa dan manajemen audio untuk acara dan pertunjukan langsung).",
        "Post-Production": "The stage of video production that occurs after shooting, including editing and effects (Tahap produksi video yang terjadi setelah pengambilan gambar, termasuk penyuntingan dan efek).",
        "Audio Fidelity": "The accuracy with which audio equipment reproduces sound (Akurasi di mana peralatan audio mereproduksi suara).",
        "Visual Effects (VFX)": "Computer-generated imagery and effects added to video footage (Gambar dan efek yang dihasilkan komputer yang ditambahkan ke rekaman video).",
        "Audio Calibration": "The process of adjusting audio equipment to achieve optimal performance (Proses menyesuaikan peralatan audio untuk mencapai kinerja optimal).",
        "Video Streaming": "The continuous delivery of video content over the internet (Pengiriman konten video secara terus-menerus melalui internet).",
        "Camera Angles": "The perspectives from which video footage is captured (Perspektif dari mana rekaman video diambil).",
        "Audio Dynamics": "The range of volume levels in an audio signal (Rentang level volume dalam sinyal audio).",
        "Color Grading": "The process of adjusting the color and tone of video footage during post-production (Proses menyesuaikan warna dan nada rekaman video selama pasca-produksi).",
        "Digital Audio Workstation (DAW)": "A software platform used for recording, editing, and producing audio (Platform perangkat lunak yang digunakan untuk merekam, mengedit, dan memproduksi audio).",
        "Video Resolution": "The amount of detail that the video image holds, often measured in pixels (Jumlah detail yang dimiliki gambar video, sering diukur dalam piksel).",
        "Surround Sound": "An audio system that creates an immersive listening experience by using multiple audio channels (Sistem audio yang menciptakan pengalaman mendengarkan yang imersif dengan menggunakan beberapa saluran audio).",
        "Audio Routing": "The process of directing audio signals from one source to another (Proses mengarahkan sinyal audio dari satu sumber ke sumber lain).",
        "Video Synchronization": "The alignment of video with audio or other video sources to ensure coherent playback (Penyelarasan video dengan audio atau sumber video lain untuk memastikan pemutaran yang koheren)."
    },
    "Teknik Permesinan (TP)": {
        "Lathe": "A machine tool used for shaping metal or wood by means of a rotating drive (Peralatan mesin yang digunakan untuk membentuk logam atau kayu dengan cara penggerak yang berputar).",
        "Milling Machine": "A machine tool used to machine solid materials by removing material from a workpiece (Peralatan mesin yang digunakan untuk memproses bahan padat dengan menghilangkan material dari benda kerja).",
        "Drilling Machine": "A machine tool used for creating holes in a workpiece by rotating a drill bit (Peralatan mesin yang digunakan untuk membuat lubang pada benda kerja dengan memutar mata bor).",
        "CNC (Computer Numerical Control)": "A method used to control machine tools via computer for precise machining (Metode yang digunakan untuk mengontrol peralatan mesin melalui komputer untuk pemesinan yang presisi).",
        "Grinding Machine": "A machine used for finishing metal surfaces by means of a rotating abrasive wheel (Peralatan mesin yang digunakan untuk menyelesaikan permukaan logam dengan roda abrasif yang berputar).",
        "Tooling": "The process of designing and manufacturing tools and dies for machining operations (Proses merancang dan memproduksi alat dan cetakan untuk operasi pemesinan).",
        "Workpiece": "The material being machined or processed (Material yang sedang diproses atau dimesin).",
        "Tolerance": "The allowable deviation from a specified dimension (Deviasi yang diperbolehkan dari dimensi yang ditentukan).",
        "Feed Rate": "The speed at which the workpiece or tool is fed into the cutting tool (Kecepatan di mana benda kerja atau alat dimasukkan ke dalam alat potong).",
        "Cutting Speed": "The speed at which the cutting tool engages with the workpiece (Kecepatan di mana alat potong berinteraksi dengan benda kerja).",
        "Turning": "A machining process where a cutting tool removes material from a rotating workpiece (Proses pemesinan di mana alat potong menghilangkan material dari benda kerja yang berputar).",
        "Milling": "A machining process where material is removed from a workpiece by rotating a cutting tool (Proses pemesinan di mana material dihilangkan dari benda kerja dengan memutar alat potong).",
        "Drilling": "The process of creating holes in a workpiece using a rotating drill bit (Proses membuat lubang pada benda kerja menggunakan mata bor yang berputar).",
        "Threading": "The process of creating threads on a workpiece using a cutting tool (Proses membuat ulir pada benda kerja menggunakan alat potong).",
        "Surface Finish": "The texture and smoothness of a machined surface (Tekstur dan kelicinan permukaan yang dimesin).",
        "Precision": "The degree of accuracy with which a machine tool can produce a part (Tingkat akurasi di mana alat mesin dapat memproduksi sebuah bagian).",
        "CAD (Computer-Aided Design)": "Software used to create detailed 2D and 3D designs for manufacturing (Perangkat lunak yang digunakan untuk membuat desain 2D dan 3D yang terperinci untuk produksi).",
        "CAM (Computer-Aided Manufacturing)": "Software used to control machine tools and automate manufacturing processes (Perangkat lunak yang digunakan untuk mengontrol peralatan mesin dan mengotomatisasi proses produksi).",
        "Fixture": "A device used to hold and support a workpiece during machining (Perangkat yang digunakan untuk menahan dan mendukung benda kerja selama pemesinan).",
        "Die": "A specialized tool used to shape or cut material during machining (Alat khusus yang digunakan untuk membentuk atau memotong material selama pemesinan).",
        "Tool Path": "The trajectory followed by a cutting tool during machining operations (Jalur yang diikuti oleh alat potong selama operasi pemesinan).",
        "Chip Removal": "The process of removing chips or shavings from the workpiece during machining (Proses menghilangkan chip atau serutan dari benda kerja selama pemesinan).",
        "Hardness": "The measure of a material's resistance to deformation or scratching (Pengukuran ketahanan material terhadap deformasi atau goresan).",
        "Milling Cutter": "A tool used in a milling machine to remove material from a workpiece (Alat yang digunakan dalam mesin milling untuk menghilangkan material dari benda kerja).",
        "Bench Lathe": "A small lathe machine designed to be used on a workbench (Mesin lathe kecil yang dirancang untuk digunakan di meja kerja).",
        "Live Center": "A device used to support the rotating end of a workpiece in a lathe (Perangkat yang digunakan untuk mendukung ujung benda kerja yang berputar dalam mesin lathe).",
        "Tool Rest": "A component of a lathe that supports the cutting tool (Komponen mesin lathe yang mendukung alat potong).",
        "Workholding": "The process of securing a workpiece in a machine tool for machining (Proses mengamankan benda kerja dalam peralatan mesin untuk pemesinan).",
        "Spindle": "The rotating axis of a machine tool that holds and drives the cutting tool (Sumbu berputar dari peralatan mesin yang memegang dan menggerakkan alat potong).",
        "Collet": "A tool holder that grips and holds a cutting tool or workpiece (Pemegang alat yang memegang dan menahan alat potong atau benda kerja).",
        "Cutting Tool": "A tool used to remove material from a workpiece (Alat yang digunakan untuk menghilangkan material dari benda kerja).",
        "Turning Center": "A type of CNC machine designed for turning operations (Jenis mesin CNC yang dirancang untuk operasi pemesinan putar).",
        "Vertical Milling Machine": "A milling machine with a vertically oriented spindle for cutting (Mesin milling dengan spindle yang terorientasi secara vertikal untuk pemotongan).",
        "Horizontal Milling Machine": "A milling machine with a horizontally oriented spindle for cutting (Mesin milling dengan spindle yang terorientasi secara horizontal untuk pemotongan).",
        "Shaping Machine": "A machine tool used for cutting and shaping metal or wood in a back-and-forth motion (Peralatan mesin yang digunakan untuk memotong dan membentuk logam atau kayu dengan gerakan maju mundur).",
        "Surface Grinder": "A machine used to grind the surface of a workpiece to achieve a smooth finish (Mesin yang digunakan untuk mengasah permukaan benda kerja untuk mencapai hasil yang halus)."
    },
    "Desain Teknik Furniture (DTF)": {
        "Furniture Design": "The art and science of creating functional and aesthetically pleasing furniture (Seni dan ilmu menciptakan furnitur yang fungsional dan estetis).",
        "Woodworking": "The process of making items from wood, including cutting, shaping, and finishing (Proses membuat barang dari kayu, termasuk memotong, membentuk, dan menyelesaikan).",
        "Joinery": "The method of connecting pieces of wood together to produce complex items (Metode menghubungkan potongan kayu bersama untuk menghasilkan barang-barang kompleks).",
        "Carpentry": "The trade of cutting and joining timber in order to construct buildings or furniture (Pekerjaan memotong dan menyambung kayu untuk membangun bangunan atau furnitur).",
        "CAD (Computer-Aided Design)": "Software used to create detailed 2D and 3D designs for furniture (Perangkat lunak yang digunakan untuk membuat desain 2D dan 3D yang terperinci untuk furnitur).",
        "Ergonomics": "The study of people's efficiency in their working environment, applied to furniture design (Studi tentang efisiensi orang di lingkungan kerja mereka, diterapkan pada desain furnitur).",
        "Finishing": "The process of applying a coating to protect and enhance the appearance of furniture (Proses menerapkan lapisan untuk melindungi dan meningkatkan penampilan furnitur).",
        "Veneer": "A thin decorative covering of fine wood applied to a coarser wood or other material (Lapisan tipis kayu halus yang diterapkan pada kayu kasar atau bahan lainnya).",
        "Upholstery": "The materials used to make a soft covering for a seat (Bahan yang digunakan untuk membuat penutup lembut untuk kursi).",
        "Cabinetmaking": "The craft of making fine furniture and cabinetry (Kerajinan membuat furnitur dan kabinet yang bagus).",
        "Wood Lathe": "A machine used to shape wood by rotating it against a cutting tool (Mesin yang digunakan untuk membentuk kayu dengan memutarnya melawan alat pemotong).",
        "Sanding": "The process of smoothing or polishing a surface with sandpaper (Proses menghaluskan atau memoles permukaan dengan amplas).",
        "Staining": "The process of applying a colored substance to wood to enhance its appearance (Proses menerapkan zat berwarna pada kayu untuk meningkatkan penampilannya).",
        "Furniture Assembly": "The process of putting together pre-made pieces to form a complete furniture item (Proses merakit potongan-potongan yang sudah dibuat menjadi barang furnitur yang lengkap).",
        "Custom Furniture": "Furniture that is designed and made to meet the specific needs of a customer (Furnitur yang dirancang dan dibuat untuk memenuhi kebutuhan spesifik pelanggan).",
        "Prototype": "An initial model or sample of a furniture design used to test and refine the concept (Model awal atau sampel dari desain furnitur yang digunakan untuk menguji dan menyempurnakan konsep).",
        "Sustainable Design": "Designing furniture with consideration for environmental impact, using eco-friendly materials and methods (Mendesain furnitur dengan mempertimbangkan dampak lingkungan, menggunakan bahan dan metode ramah lingkungan).",
        "Furniture Hardware": "The various fittings, such as hinges and handles, used in furniture making (Berbagai kelengkapan, seperti engsel dan pegangan, yang digunakan dalam pembuatan furnitur).",
        "CNC Router": "A computer-controlled machine used for cutting and shaping wood and other materials (Mesin yang dikendalikan komputer yang digunakan untuk memotong dan membentuk kayu dan bahan lainnya).",
        "Furniture Restoration": "The process of repairing and refurbishing old or damaged furniture (Proses memperbaiki dan memperbarui furnitur yang lama atau rusak).",
        "Drafting": "The process of drawing the detailed plans for furniture design (Proses menggambar rencana terperinci untuk desain furnitur).",
        "Furniture Blueprint": "A detailed drawing or plan that outlines the specifications and construction of a piece of furniture (Gambar atau rencana terperinci yang menguraikan spesifikasi dan konstruksi sebuah furnitur).",
        "Modular Furniture": "Furniture that is designed in separate pieces that can be assembled in various ways (Furnitur yang dirancang dalam potongan-potongan terpisah yang dapat dirakit dengan berbagai cara).",
        "Furniture Trends": "Current styles and innovations in furniture design (Gaya dan inovasi terkini dalam desain furnitur).",
        "Load-Bearing Capacity": "The maximum weight that a piece of furniture can safely support (Berat maksimum yang dapat ditopang oleh sebuah furnitur dengan aman).",
        "Aesthetic": "The principles of beauty and artistic taste applied to furniture design (Prinsip-prinsip keindahan dan selera artistik yang diterapkan pada desain furnitur).",
        "Miter Joint": "A joint made by beveling each of two parts to be joined, usually at a 45° angle, to form a corner (Sambungan yang dibuat dengan memotong miring masing-masing dari dua bagian yang akan disambung, biasanya pada sudut 45°, untuk membentuk sudut).",
        "Tenon and Mortise": "A woodworking joint made by inserting a projecting tenon into a corresponding mortise (Sambungan pertukangan kayu yang dibuat dengan memasukkan tenon yang menonjol ke dalam mortise yang sesuai).",
        "Dovetail Joint": "A joint used in woodworking where two pieces interlock in a series of wedge-shaped elements (Sambungan yang digunakan dalam pertukangan kayu di mana dua potongan saling mengunci dalam serangkaian elemen berbentuk baji).",
        "Furniture Prototype": "An initial full-scale model used to test the design and functionality of a furniture piece (Model skala penuh awal yang digunakan untuk menguji desain dan fungsi sebuah furnitur).",
        "Furniture CAD Model": "A digital 3D representation of a furniture design created using CAD software (Representasi 3D digital dari desain furnitur yang dibuat menggunakan perangkat lunak CAD).",
        "Furniture Finishes": "The final surface treatment applied to furniture to protect and enhance its appearance (Perlakuan permukaan akhir yang diterapkan pada furnitur untuk melindungi dan meningkatkan penampilannya).",
        "Furniture Manufacturing": "The industrial process of producing furniture on a large scale (Proses industri pembuatan furnitur dalam skala besar).",
        "Furniture Installation": "The process of placing and securing furniture in its intended location (Proses menempatkan dan mengamankan furnitur di lokasi yang diinginkan).",
        "Furniture Drafting": "The creation of detailed technical drawings and plans for furniture (Pembuatan gambar teknis dan rencana terperinci untuk furnitur).",
        "Ergonomic Furniture": "Furniture designed to provide optimal comfort and efficiency for the user (Furnitur yang dirancang untuk memberikan kenyamanan dan efisiensi optimal bagi pengguna).",
        "Furniture Material": "The raw materials used in the construction of furniture, such as wood, metal, or plastic (Bahan mentah yang digunakan dalam konstruksi furnitur, seperti kayu, logam, atau plastik).",
        "Load Testing": "The process of testing furniture to ensure it can withstand the required weight and usage (Proses pengujian furnitur untuk memastikan dapat menahan berat dan penggunaan yang diperlukan).",
        "Furniture Joinery": "The techniques and methods used to join pieces of wood together in furniture making (Teknik dan metode yang digunakan untuk menyambung potongan kayu bersama dalam pembuatan furnitur).",
        "Furniture Assembly Line": "An industrial setup where furniture is assembled in a sequence of operations (Pengaturan industri di mana furnitur dirakit dalam urutan operasi).",
        "Softwood": "Wood from coniferous trees, often used in furniture making (Kayu dari pohon konifer, sering digunakan dalam pembuatan furnitur).",
        "Hardwood": "Wood from broad-leaved trees, typically used for high-quality furniture (Kayu dari pohon berdaun lebar, biasanya digunakan untuk furnitur berkualitas tinggi).",
        "Laminate": "A thin layer of material bonded to a surface to provide a decorative or protective finish (Lapisan tipis material yang direkatkan pada permukaan untuk memberikan hasil akhir dekoratif atau pelindung).",
        "Plywood": "A strong, durable wood product made by gluing together thin layers of wood veneer (Produk kayu yang kuat dan tahan lama yang dibuat dengan merekatkan lapisan tipis kayu veneer).",
        "Furniture Design Principles": "The fundamental concepts and guidelines for creating functional and aesthetically pleasing furniture (Konsep dan pedoman dasar untuk menciptakan furnitur yang fungsional dan estetis).",
        "Furniture Prototyping": "The process of creating a preliminary model of a furniture piece for testing and refinement (Proses membuat model awal sebuah furnitur untuk pengujian dan penyempurnaan).",
        "Workshop Safety": "The practices and precautions taken to ensure a safe working environment in a furniture workshop (Praktik dan tindakan pencegahan yang diambil untuk memastikan lingkungan kerja yang aman di bengkel furnitur)."
    },
"Teknik Konstruksi Perumahan (TKP)": {
        "Architectural Design": "The process of creating plans and specifications for residential buildings (Proses membuat rencana dan spesifikasi untuk bangunan perumahan).",
        "Blueprint": "A detailed technical drawing that outlines the design, dimensions, and construction of a building (Gambar teknis terperinci yang menguraikan desain, dimensi, dan konstruksi sebuah bangunan).",
        "Foundation": "The lowest part of a building, which supports the structure and transfers its load to the ground (Bagian terendah dari bangunan, yang mendukung struktur dan mentransfer bebannya ke tanah).",
        "Load-Bearing Wall": "A wall that supports the weight of the structure above it (Dinding yang menopang berat struktur di atasnya).",
        "Framing": "The construction of the skeleton of a building using wood, steel, or concrete (Konstruksi kerangka sebuah bangunan menggunakan kayu, baja, atau beton).",
        "Insulation": "Material used to reduce heat loss or gain and provide soundproofing (Material yang digunakan untuk mengurangi kehilangan atau penyerapan panas dan memberikan kedap suara).",
        "Drywall": "A construction material used to create walls and ceilings (Material konstruksi yang digunakan untuk membuat dinding dan langit-langit).",
        "Roofing": "The process of covering the top of a building to protect it from the elements (Proses menutup bagian atas bangunan untuk melindunginya dari elemen).",
        "Siding": "Material applied to the exterior of a building to protect it and enhance its appearance (Material yang diterapkan pada eksterior bangunan untuk melindunginya dan meningkatkan penampilannya).",
        "Plumbing": "The system of pipes and fixtures installed in a building for the distribution of water and removal of waste (Sistem pipa dan perlengkapan yang dipasang dalam sebuah bangunan untuk distribusi air dan pembuangan limbah).",
        "Electrical Wiring": "The installation of electrical cables and fixtures in a building to provide power (Pemasangan kabel dan perlengkapan listrik dalam sebuah bangunan untuk menyediakan daya).",
        "HVAC (Heating, Ventilation, and Air Conditioning)": "The system used to regulate the indoor climate of a building (Sistem yang digunakan untuk mengatur iklim dalam ruangan sebuah bangunan).",
        "Concrete": "A strong building material made from a mixture of cement, sand, gravel, and water (Material bangunan yang kuat yang terbuat dari campuran semen, pasir, kerikil, dan air).",
        "Bricklaying": "The process of constructing walls and other structures using bricks (Proses membangun dinding dan struktur lainnya menggunakan batu bata).",
        "Masonry": "The craft of building structures from individual units of stone, brick, or concrete blocks (Kerajinan membangun struktur dari unit individu batu, batu bata, atau blok beton).",
        "Trusses": "Frameworks, typically consisting of rafters, posts, and struts, supporting a roof, bridge, or other structure (Rangka, biasanya terdiri dari kasau, tiang, dan penopang, yang mendukung atap, jembatan, atau struktur lainnya).",
        "Building Codes": "Regulations that specify standards for constructed objects such as buildings (Peraturan yang menentukan standar untuk objek yang dibangun seperti bangunan).",
        "Permit": "An official document giving someone authorization to build or modify a structure (Dokumen resmi yang memberikan izin kepada seseorang untuk membangun atau memodifikasi struktur).",
        "Surveying": "The process of measuring and mapping the land and its features (Proses mengukur dan memetakan tanah dan fitur-fiturnya).",
        "Zoning": "Laws that define how property in specific geographic zones can be used (Hukum yang mendefinisikan bagaimana properti di zona geografis tertentu dapat digunakan).",
        "Footing": "The part of a foundation that transfers the load to the ground (Bagian dari fondasi yang mentransfer beban ke tanah).",
        "Beam": "A structural element that primarily resists loads applied laterally to its axis (Elemen struktural yang terutama menahan beban yang diterapkan secara lateral pada sumbunya).",
        "Joist": "A horizontal structural element used to support a ceiling or floor (Elemen struktural horizontal yang digunakan untuk mendukung langit-langit atau lantai).",
        "Facade": "The front of a building, especially one that is decorative or impressive (Bagian depan bangunan, terutama yang dekoratif atau mengesankan).",
        "Cladding": "A covering or coating on a building to provide thermal insulation and weather resistance (Penutup atau pelapisan pada bangunan untuk memberikan isolasi termal dan ketahanan cuaca).",
        "Retaining Wall": "A structure that holds or retains soil behind it (Struktur yang menahan atau menahan tanah di belakangnya).",
        "Sustainable Building": "Construction practices that are environmentally responsible and resource-efficient (Praktik konstruksi yang bertanggung jawab terhadap lingkungan dan efisien sumber daya).",
        "Prefab": "Building components that are manufactured in a factory and assembled on-site (Komponen bangunan yang diproduksi di pabrik dan dirakit di lokasi).",
        "Site Plan": "A detailed architectural plan showing the layout of buildings and infrastructure on a plot of land (Rencana arsitektur terperinci yang menunjukkan tata letak bangunan dan infrastruktur di sebidang tanah).",
        "Scaffolding": "Temporary structures used to support workers and materials during construction (Struktur sementara yang digunakan untuk mendukung pekerja dan material selama konstruksi).",
        "Load Calculation": "The process of determining the weight that a building structure must support (Proses menentukan berat yang harus didukung oleh struktur bangunan).",
        "Rafter": "One of a series of sloped beams that extend from the ridge or hip to the wall plate, down the slope of the roof (Salah satu dari serangkaian balok miring yang memanjang dari punggungan atau pinggul ke plat dinding, turun di lereng atap).",
        "Subfloor": "The structural layer that supports the finished floor covering (Lapisan struktural yang mendukung penutup lantai yang selesai).",
        "Retrofitting": "The process of adding new technology or features to older buildings (Proses menambahkan teknologi atau fitur baru ke bangunan yang lebih tua).",
        "Drainage": "The system or process by which water is drained away from a building (Sistem atau proses di mana air dialirkan dari bangunan).",
        "Punch List": "A document listing work that does not conform to contract specifications and must be completed before final payment (Dokumen yang mencantumkan pekerjaan yang tidak sesuai dengan spesifikasi kontrak dan harus diselesaikan sebelum pembayaran akhir).",
        "Dry Rot": "A type of decay in timber caused by fungi that result in the wood becoming dry and crumbly (Jenis pembusukan pada kayu yang disebabkan oleh jamur yang membuat kayu menjadi kering dan rapuh).",
        "Building Envelope": "The physical separator between the interior and exterior of a building (Pemisa fisik antara interior dan eksterior bangunan).",
        "Eaves": "The part of a roof that meets or overhangs the walls of a building (Bagian dari atap yang bertemu atau menggantung di dinding bangunan).",
        "Green Building": "Building practices that reduce the environmental impact of construction (Praktik bangunan yang mengurangi dampak lingkungan dari konstruksi).",
        "Infill": "The development of vacant or underused parcels within existing urban areas (Pengembangan lahan kosong atau kurang dimanfaatkan dalam area perkotaan yang ada).",
        "Load Distribution": "The way in which the load is spread over a structure (Cara di mana beban tersebar di atas struktur).",
        "Lintel": "A horizontal support of timber, stone, concrete, or steel across the top of a door or window (Penopang horizontal dari kayu, batu, beton, atau baja di bagian atas pintu atau jendela).",
        "Passive Solar Design": "Designing buildings to take advantage of natural sunlight for heating and lighting (Mendesain bangunan untuk memanfaatkan sinar matahari alami untuk pemanasan dan penerangan).",
        "Rebar": "Steel bars used to reinforce concrete (Batang baja yang digunakan untuk memperkuat beton).",
        "Site Preparation": "The process of making a construction site ready for building (Proses membuat situs konstruksi siap untuk dibangun).",
        "Structural Integrity": "The ability of a building to withstand its intended load without failing (Kemampuan sebuah bangunan untuk menahan beban yang dimaksudkan tanpa gagal).",
        "Truss": "A framework of beams forming a rigid structure (Kerangka balok yang membentuk struktur kaku).",
        "Utility Services": "The infrastructure that provides essential services such as water, electricity, and sewage (Infrastruktur yang menyediakan layanan penting seperti air, listrik, dan pembuangan limbah).",
        "Weatherproofing": "The process of making a building resistant to the effects of weather (Proses membuat sebuah bangunan tahan terhadap efek cuaca).",
        "Wind Load": "The force exerted by wind on a structure (Gaya yang diberikan oleh angin pada sebuah struktur).",
        "Zone": "A specifically designated area within a city or municipality for certain types of development and land use (Area yang secara khusus ditetapkan dalam sebuah kota atau kotamadya untuk jenis pengembangan dan penggunaan lahan tertentu)."
    }
}
